;;; tagedit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tagedit.el

(autoload 'tagedit-add-paredit-like-keybindings "tagedit" nil t)
(autoload 'tagedit-add-experimental-features "tagedit")
(autoload 'tagedit-disable-experimental-features "tagedit")
(autoload 'tagedit-insert-equal "tagedit" nil t)
(autoload 'tagedit-insert-quote "tagedit" nil t)
(autoload 'tagedit-insert-lt "tagedit" nil t)
(autoload 'tagedit-insert-hash "tagedit" nil t)
(autoload 'tagedit-insert-dot "tagedit" nil t)
(autoload 'tagedit-insert-gt "tagedit" nil t)
(autoload 'tagedit-insert-exclamation-mark "tagedit" nil t)
(autoload 'tagedit-maybe-insert-slash "tagedit" nil t)
(autoload 'tagedit-kill "tagedit" nil t)
(autoload 'tagedit-forward-slurp-tag "tagedit" nil t)
(autoload 'tagedit-forward-barf-tag "tagedit" nil t)
(autoload 'tagedit-kill-attribute "tagedit" nil t)
(autoload 'tagedit-toggle-multiline-tag "tagedit" nil t)
(autoload 'tagedit-raise-tag "tagedit" nil t)
(register-definition-prefixes "tagedit" '("tagedit-" "te/"))

;;; End of scraped data

(provide 'tagedit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tagedit-autoloads.el ends here
